syntax on
filetype on

"ctags
set tags=tags

set ru
set si
set ai
set hls
set number
set nocp
set laststatus=2
set backspace=indent,eol,start
:color desert

"set csprg="/usr/local/bin/cscope"

source ~/.vim/plugin/.cscope_maps.vim
